### PR TITLE
feat: add pre-commit hooks

### PR DESCRIPTION
**Pull request by Freed-Wu**
Refer https://pre-commit.com/

### CODE REVIEW

**Comment by Decodetalkers** [comment]
What is it for? Will it do cargo fmt every time before commit

**Comment by Freed-Wu** [comment]
https://pre-commit.com/#rust

**Comment by Freed-Wu** [comment]
Firstly, it will download git repo then `cargo build`. Then every time `git commit`, it will call `neocmakelsp format` for all cmake files.

**Comment by Freed-Wu** [comment]
For example: https://github.com/cmake-lint/cmake-lint/blob/develop/.pre-commit-hooks.yaml

**Comment by Decodetalkers** [comment]
> For example: https://github.com/cmake-lint/cmake-lint/blob/develop/.pre-commit-hooks.yaml

Emm, the cmake files under this repo is just for test, you should not do anything for it

**Comment by Freed-Wu** [comment]
Oh, I means it is an example of pre-commit hooks. :smile:

**Comment by Decodetalkers** [comment]
> Oh, I means it is an example of pre-commit hooks. :smile:

Ha, I see, you can create a folder named contribute, put it in this fold, and not use `.name`, change it to example-precommit.yaml, then it will be ok

**Comment by Freed-Wu** [comment]
Oh, pre-commit always search file named `.pre-commit-hooks.yaml`, not `contribute/example-precommit.yaml` :cry:

**Comment by Decodetalkers** [comment]
> Oh, pre-commit always search file named `.pre-commit-hooks.yaml`, not `contribute/example-precommit.yaml` :cry:

But it is an example, not the config of the project, so this one should be used for other repo, not this one, if you put it in the root of the project, pre-commit will work for this project

**Comment by Freed-Wu** [comment]
> not the config of the project,

Do you means `.pre-commit-config.yaml`? Every linter/formatter repo have a `.pre-commit-hooks.yaml` in the root of repo, Every project use the linter/formatter will have a `.pre-commit-config.yaml` in the root of their repo.

**Comment by Decodetalkers** [comment]
Ok, I see, get it

**Comment by Decodetalkers** [comment]
Thank you very much

**Pull request merged**
